### PR TITLE
Update Simlified_Chinese.properties

### PR DESCRIPTION
**Pull request by heipizhu4**
I've just left for a few days, and the mod and its template changed so much. That's why I restarted my translation completely.

### CODE REVIEW

**Comment by heipizhu4** [comment]
Translation process +2%. I am going to sleep. You can either merge it or leave it until I make the next commit.

**Comment by carriontrooper** [comment]
alrighty, merged!

**Comment by carriontrooper** [comment]
also keep in mind that there might be more buildings/wonders on the way - the template will be added to.

**Comment by heipizhu4** [comment]
Thanks, I will.

**Pull request merged**
